### ISSUE TITLE
Unit of RR interval value in the label csv file.

### ISSUE THREAD

**Issue by popobaboya** [al3xsh/rnn-based-af-detection#1]
Hello, I got a question while looking your codes and files. 
I'd appreciate it if you could answer.

1. Is the unit of RR interval values in the training and verification csv file 'ms'? 
2. Nearly half of the cases are classified as arrhythmia in the csv file, it this intended for training?
(the case it's greater than 0)
* I understood that if it is greater than 0, it is converted to 1, and 1 is used as a label that means arrhythmia during training.

**Comment by al3xsh** [comment]
1. Yes
2. Which CSV file? Overall approximately 45% of the 100 beat sequences exhibited some sign of atrial fibrillation according to the beat annotations in the MIT-BIH AF database - https://physionet.org/content/afdb/1.0.0/. 

(The label denotes the number of beats in that sequence that were classified as AF).

Alex

**Comment by popobaboya** [comment]
Hello, I have a new question and would like to ask.
I'd appreciate it if you could answer.

Q : Is each value of train data RR interval ? (Like 04015_label_100_data.csv)

Since a person's heart rate is 60-100 per minute on average, the average of RR interval would be 0.6-1 s.

![image](https://user-images.githubusercontent.com/61726550/148379112-6194a3af-3648-4411-a63f-bd5f38298376.png)

And this is the RR interval time series of the record '04015' (corrected beat annotation).
Reference : https://archive.physionet.org/cgi-bin/atm/ATM
Most of RR intervals are between 0.5 and 1(sec).

However, in the csv file, the values are too small. it's average is just about 205(ms).

So I think I misunderstood the values as RR interval or missed some process.
I would really appreciate it if you could let me know why those values are small.
